# File: src/main/resources/application.properties

spring.application.name=FundAxis
server.port=8080

# ---------- SQL Server connection ----------
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=fundaxis;encrypt=true;trustServerCertificate=true
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ---------- JPA / Hibernate ----------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
